### ISSUE TITLE
Input Bits

### ISSUE THREAD

**Issue by Zeeshan2901** [emp-toolkit/emp-ag2pc#10]
Hi, I am using your paper and emp-ag2pc tool for a project and I encountered an issue (rather say a doubt). When I am running a simple circuit (just and gates) on inputs of different bits (2 bit for Alice and 1 bit for Bob), I am not getting desired outputs and sometimes segmentation fault error.

**Alice input:** 1 1
**Bob Input:** 0

**Circuit File:**
3 6
2 1 3

2 1 0 2 3 AND
2 1 1 2 4 AND
2 1 0 1 5 AND

I have attached my test file and execution logs.

The expected output is **0 0 1**, but with every execution I am getting different outputs.

I am assuming that the order of input wires in the circuit follows from 0 to n-1 for Alice and henceforth for Bob.

![executionlog](https://user-images.githubusercontent.com/23634022/64392398-ffc3d380-d022-11e9-99ac-076e27009e23.png)
![file](https://user-images.githubusercontent.com/23634022/64392399-ffc3d380-d022-11e9-96fb-81a8ba8c0040.png)

**Comment by wangxiao1254** [comment]
Can you please first try it out on emp-tool or emp-sh2pc to make sure that
the circuit format is correctly interpreted by EMP? In this way, we can
pinpoint where the problem is.

Thanks,
Xiao

**Comment by Zeeshan2901** [comment]
Fixed the issue. The issue was with the ordering of output lines. Hence closing the issue.
