### ISSUE TITLE
Run's out of memory for large circuits

### ISSUE THREAD

**Issue by nitincic** [emp-toolkit/emp-ag2pc#11]
The implementation seems to run out of memory during the function independent phase for circuits of size >10^8 ((|C| > 2^27). Is that an expected behaviour? or probably I'm doing something wrong?

**Comment by wangxiao1254** [comment]
Yes.
The function independent phase needs to generate all authenticated AND
triples and store them in memory. That's why memory usage is relevant here.
There are ways to generate triples batch-by-batch, but they are not
implemented in the current version.

**Comment by nitincic** [comment]
I see, thanks.
