### ISSUE TITLE
How can both parties receive the output?

### ISSUE THREAD

**Issue by benediamond** [emp-toolkit/emp-ag2pc#13]
Hi Xiao, thanks for your incredible work as always.

As the code is written, it appears that only Bob receives the output. You can test this by setting `in[0] = true;` after
https://github.com/emp-toolkit/emp-ag2pc/blob/163985c8a1637f64a1d1cfc5f75214d6d8ef06da/test/single_execution.h#L25
and removing the condition
https://github.com/emp-toolkit/emp-ag2pc/blob/163985c8a1637f64a1d1cfc5f75214d6d8ef06da/test/single_execution.h#L32
and finally running `./bin/simple_circuit 1 12345 & ./bin/simple_circuit 2 12345` (Bob will receive 000010 and Alice 000000).

Of course Bob could just send Alice the output after the protocol is done, but then she wouldn't trust its correctness.

Please let me know if there is an easy way to address this. Thanks!

**Comment by wangxiao1254** [comment]
The protocol currently on support one party getting the output, there are
easy ways to fix it but I will probably fix it in the next iteration of the
protocol in the branch release-2. The issue is that we need an interface to
specify who to reveal to, but the current circuit format does not provide
such functionality...

**Comment by benediamond** [comment]
@wangxiao1254 thanks for the response.

Yes, perhaps an unobtrusive approach would be to add extra numbers to the second line of `output.gate.txt` indicating (ranges for) Alice's output wires, Bob's, and Public output wires. For example,
```
n1 n2 n3 a b
```
would mean that among the `n3` output wires, `[0 : a - 1]` are public, `[a : b - 1]` are Alice's, and `[b : n3 - 1]` are Bob's. or something like that. thanks again.

**Comment by benediamond** [comment]
A simpler (though less flexible) approach could be to add a parameter to the `C2PC` object, which controls whether the outputs are Public or Bob-only.

**Comment by wangxiao1254** [comment]
this is supported now. A switch is added to allow all parties to get the output. A more flexible way to handle output will be implemented in the next iteration.
