### ISSUE TITLE
incorrect output using ag2pc

### ISSUE THREAD

**Issue by kzhong130** [emp-toolkit/emp-ag2pc#18]
Hi, I am trying out ag2pc to run a simple application (addition with values from two party). It turns out that the results after I reveal are incorrect. I have provided codes and detailed description in this repo: https://github.com/kzhong130/emp-ag2pc-max-example. I think this is related to @issue8 but not exactly the same. Thank you! Please let me know if there is anything unclear.

**Comment by weikengchen** [comment]
(Can you also attach a Makefile or something for the compilation commands?)

**Comment by kzhong130** [comment]
Sure, for max-circuit-gen.cpp, I add that to the test directory of emp-tool repo, and then add a line "add_test(max-circuit-gen)" to the end of CMakeLists.txt in emp-tool repo. And for max-ag2.cpp, I do the same thing on emp-ag2pc repo. I can quickly fork those two repos and put the files under them, if that makes things easier. But that might require you complie/install the emp-tool & emp-ag2pc again? Please let me know which way works best for you, thank you!

**Comment by weikengchen** [comment]
I reproduced a similar incorrect result:
A[0]: 4
A[1]: 6
A[2]: 2
B[0]: 5
B[1]: 1
B[2]: 3
A[0]+B[0]: 9
A[1]+B[1]: 7
A[2]+B[2]: 5

with the modification that A[0]+B[0] follows a different order.

I am on the way to look into it...

**Comment by kzhong130** [comment]
Ah, sorry, I think we got the same result. I made a typo when pasting the results of A[i]+B[i]. Have pushed to my repo.

**Comment by wangxiao1254** [comment]
I may not be able to take a look this week, but I suggest first using sh2pc
to run the circuit. This makes sure nothing wrong with the circuit or how
input is encoded.

Xiao

**Comment by weikengchen** [comment]
Made a pull request here: https://github.com/kzhong130/emp-ag2pc-max-example/pull/1

It seems that the current plaintext engine demands Alice's input be allocated before Bob's input.

**Comment by kzhong130** [comment]
Works now! Thank you so much. Sorry that I did not find any related stuff to that requirement before... So I am following another survey repo for this tool: https://github.com/MPC-SoK/frameworks/wiki/EMP-toolkit. In their example it seems find to just allocate both inputs in one loop. So maybe it would be great to mention that there as well.

**Comment by weikengchen** [comment]
I would say it is a limitation of `emp-tool` at this moment. The Bristol fashion circuits are not easy to work with. (This might be changed in the coming years.)
