### ISSUE TITLE
Problem with amortized_2pc

### ISSUE THREAD

**Issue by dalmayr777** [emp-toolkit/emp-ag2pc#19]
There seems to be a bug in `amortized_2pc.cpp`, or I have misunderstanding on how to call it. I have freshly cloned and compiled `emp-tool`, `emp-ot`, and `emp-ag2pc `in` /tmp`.

```
user@tra:/tmp/emp-ag2pc (master)$ ./run bin/aes
connected
connected
128 128 128 6800
128 128 128 6800
one time:	1	29312
one time:	2	30083
ABIT	4598
check	2952
permute	927
inde:	1	9765
inde:	2	9247
dep:	2	6505
dep:	1	6777
online:	2	749
online:	1	756

```

Looking good. Now I would like to run `amortized_2pc`. First, `sha-1.txt` is there:
```
user@tra:/tmp/emp-ag2pc (master)$ ls /tmp/emp-tool/emp-tool/circuits/files/bristol_format//sha-1.txt
/tmp/emp-tool/emp-tool/circuits/files/bristol_format//sha-1.txt
```

However, calling amortized_2pc fails.

```
user@tra:/tmp/emp-ag2pc (master)$ ./run bin/amortized_2pc 
connected
connected
one time:	1	27762
one time:	2	27824
ABIT	576
check	969
permute	431
inde:	1	13281
inde:	2	12942
./run: line 29: 188700 Segmentation fault      $1 1 12345
./run: line 30: 188698 Segmentation fault      $1 2 12345
```
Interestingly, if I change the line which says
`const static int runs = 4;
`
to
`const static int runs = 1;
`
then the binary does not crash, but I get a lot of 
`no match GT!
`
errors in the console output.

What am I doing wrong?

**Comment by dalmayr777** [comment]
Here is GDB's output for the segfault:

```
Thread 2 "amortized_2pc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff72e2700 (LWP 10550)]
0x00005555555d50c6 in emp::AmortizedC2PC<emp::NetIO, 4>::function_dependent_thread (this=0x7fffffffdf30, e=1, I=0)
    at /home/erik/emp/emp-ag2pc/emp-ag2pc/amortized_2pc.h:370
370                                     x1[e][ands] = getLSB(mac[e][cf->gates[4*i]] ^ ANDS_mac[e][3*ands]);

```

Is this helpful? Actually, anybody should get this segfault using MASTER...

**Comment by wangxiao1254** [comment]
We recently upgraded the COT in this repo to FERRET. It might have something to do with that. I will take a look when I got the time!

**Comment by dalmayr777** [comment]
Could you give me a recommendation to which commit I should go back in emp-ag2pc, emp-tool, and emp-ot to make it run? :smiley:

**Comment by wangxiao1254** [comment]
fixed!

**Comment by dalmayr777** [comment]
Works, thanks a lot!
