### ISSUE TITLE
on travis failure when that vm does not have bmi2

### ISSUE THREAD

**Issue by weikengchen** [emp-toolkit/emp-ag2pc#2]
I found that it is a little bit random whether bmi2 instructions are supported in that Travis VM.

For those VMs that bmi2 is listed in CPU support, they are okay. For others, they fail.

I mean, can ignore Travis for a while

**Comment by weikengchen** [comment]
https://github.com/emp-toolkit/emp-ag2pc/pull/3

This is a fix.

**Comment by weikengchen** [comment]
and here is the information about the CPU we will encounter from Travis:

For the n1 series of machine types, a virtual CPU is implemented as a single hardware hyper-thread on a 2.6 GHz Intel Xeon E5 (Sandy Bridge), 2.5 GHz Intel Xeon E5 v2 (Ivy Bridge), 2.3 GHz Intel Xeon E5 v3 (Haswell), 2.2 GHz Intel Xeon E5 v4 (Broadwell), or 2.0 GHz Intel Skylake (Skylake).

**Comment by wangxiao1254** [comment]
Maybe as you can see, I almost gave up making it pass all travis test :)

**Comment by wangxiao1254** [comment]
Seems it is already fixed long ago (by you).
