### ISSUE TITLE
emp-ag2pc no longer compiles: small issue with "triple" test

### ISSUE THREAD

**Issue by rdeviti** [emp-toolkit/emp-ag2pc#21]
Hi, just wanted to let you know that this recent commit in emp-tool:
https://github.com/emp-toolkit/emp-tool/commit/fa237b785838732cdd49a56f7c75b7e6c80f76ae

Has an impact on test/triple.cpp. It's not just the additional port now needed in the HighSpeedNetIO constructor: fpre assumes that the input io has an io->addr, which has been removed from HighSpeedNetIO. 

This is the only dependency afaik, it compiles just fine without the "triple" test.

**Comment by wangxiao1254** [comment]
fixed!
