### ISSUE TITLE
class C2PC does not accept FileIO type

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ag2pc#23]
Hi, thank you for your work in MPC research and for making this tool available.
I was trying to compile ag2pc into wasm and realized that I can't pass FileIO here;

https://github.com/emp-toolkit/emp-ag2pc/blob/b93a28aa84eb7d353d6a775f57030fb7187f9c04/emp-ag2pc/2pc.h#L28

Even though it is a template, it only works with NetIO and with FileIO I get erros like:
`emp-ag2pc/fpre.h:51:51: error: no member named 'addr' in 'emp::FileIO'`

Is it correct that FileIO could be passed to the constructor and then a file could be used for client<->server communication? That would be useful for my project.

**Comment by wangxiao1254** [comment]
Nope, FileIO only do file I/O from and to a file
