### ISSUE TITLE
transmitting authenticated circuit in online phase

### ISSUE THREAD

**Issue by themighty1** [emp-toolkit/emp-ag2pc#24]
Hi, I'm looking at the online phase https://github.com/emp-toolkit/emp-ag2pc/blob/b93a28aa84eb7d353d6a775f57030fb7187f9c04/emp-ag2pc/2pc.h#L274
and all I can see is that data related to parties's inputs is transmitted.
The paper says that the authenticated circuit is transmitted in the online phase

> ...the parties in our protocol use this information in the online phase to
> generate a single “authenticated” garbled circuit. As in the semi-honest case, this garbled circuit can then
> be transmitted and evaluated in just one additional round.

Am I misunderstanding the paper? At what stage is the authenticated circuit transmitted?

**Comment by wangxiao1254** [comment]
the garbled circuit is transmitted in the function-dependent phase.
