### ISSUE TITLE
malicious is hardcoded to false?

### ISSUE THREAD

**Issue by voltrevo** [emp-toolkit/emp-ag2pc#40]
It looks LeakyDeltaOT hardcodes IKNP's malicious parameter as false. Does this disable malicious security?

```c++
class LeakyDeltaOT: public IKNP<T> { public:
	LeakyDeltaOT(T * io): IKNP<T>(io, false){ // <--- here
	}
```

https://github.com/emp-toolkit/emp-ag2pc/blob/1975122/emp-ag2pc/leaky_deltaot.h#L14

**Comment by wangxiao1254** [comment]
As shown in https://eprint.iacr.org/2019/1104.pdf Section 3.1, one can use COTe rather than COT in the context of computing authenticated bits.

**Comment by voltrevo** [comment]
@wangxiao1254 Oh ok. Does `C2PC` (from 2pc.h) use COTe? Specifying malicious:true in IKNP is redundant?

**Comment by wangxiao1254** [comment]
IKNP without malicious checks is COTe

**Comment by voltrevo** [comment]
Ok thanks
